#!/bin/bash

progress () { echo "====== $@" ; }

# Executables
# -----------

repo_dir="$(cd "$(dirname "$0")"; pwd)"
rvmonitor_bin="$repo_dir/ext/rv-monitor/target/release/rv-monitor/bin"
javamop_bin="$repo_dir/ext/javamop/target/release/javamop/javamop/bin"
specs_dir="$repo_dir/test/resources"

progress "generate aspectJ and rvm files"

( cd "$repo_dir/src/test/resources" && \
  "$javamop_bin/javamop" -merge *.mop && \
  mkdir -p classes/mop && \
  "$rvmonitor_bin/rv-monitor" -merge -d classes/mop/ *.rvm && \
  javac classes/mop/MultiSpec_1RuntimeMonitor.java && \
  rm rm classes/mop/MultiSpec_1RuntimeMonitor.java && \
  javamop_bin/javamopagent MultiSpec_1MonitorAspect.aj classes -n JavaMOPAgent -excludeJars )

